export const data2 = [
    {"kelime":"Engine","isim":"Motor","sifat":"","zarf":"","fiil":"","okunus":"enjın","resimYol":"engine.jpg","btnSmile":false,"btnThink":false,"btnAngry":false,"knowNumber":-1},
    {"kelime":"Simple","isim":"","sifat":"Basit, Kolay","zarf":"","fiil":"","okunus":"sımpıl","resimYol":"simple.jpg","btnSmile":false,"btnAngry":false,"btnThink":false,"knowNumber":1},
    {"kelime":"Scale","isim":"ölçek","sifat":"","zarf":"","fiil":"","okunus":"skeyl","resimYol":"scale.jpg","btnSmile":false,"btnAngry":false,"btnThink":false,"knowNumber":0},
    {"kelime":"Expect","isim":"","sifat":"","zarf":"","fiil":"beklemek","okunus":"ekspekt","resimYol":"expect.png","btnSmile":false,"btnAngry":false,"btnThink":false,"knowNumber":0},
    {"kelime":"Preview","isim":"","sifat":"","zarf":"","fiil":"","okunus":"pridiu","resimYol":"Preview.jpg","btnSmile":false,"btnAngry":false,"btnThink":false,"knowNumber":0},
    {"kelime":"Remain","isim":"","sifat":"","zarf":"","fiil":"Kalmak","okunus":"rimeyn","resimYol":"remain.png","btnSmile":false,"btnAngry":false,"btnThink":false,"knowNumber":1},
    {"kelime":"Validation","isim":"onaylama","sifat":"","zarf":"","fiil":"","okunus":"velideşın","resimYol":"validation.jpg","btnSmile":false,"btnAngry":false,"btnThink":false,"knowNumber":1},
    {"kelime":"Place","isim":"yer","sifat":"","zarf":"","fiil":"","okunus":"pleys","resimYol":"Place.jpg","btnSmile":false,"btnAngry":false,"btnThink":false,"knowNumber":0},
    {"kelime":"Lasting","isim":"","sifat":"kalıcı","zarf":"","fiil":"","okunus":"lasting","resimYol":"lasting.jpg","btnSmile":false,"btnAngry":false,"btnThink":false,"knowNumber":0},
    {"kelime":"Arrow","isim":"Ok","sifat":"","zarf":"","fiil":"","okunus":"erow","resimYol":"arrow.jpg","btnSmile":false,"btnAngry":false,"btnThink":false,"knowNumber":1},
    {"kelime":"Beast","isim":"canavar, hayvan","sifat":"","zarf":"","fiil":"","okunus":"biist","resimYol":"beast.png","btnSmile":false,"btnAngry":false,"btnThink":false,"knowNumber":0},
    {"kelime":"Clap","isim":"alkış","sifat":"","zarf":"","fiil":"alkışlamak","okunus":"klaep","resimYol":"clap.jpg","btnSmile":false,"btnAngry":false,"btnThink":false,"knowNumber":0},
    {"kelime":"Fire","isim":"Yangın, ateş","sifat":"","zarf":"","fiil":"kovmak, ateşlemek","okunus":"fayr","resimYol":"fire.1507584571.jpg","btnSmile":false,"btnAngry":false,"btnThink":false,"knowNumber":2},
    {"kelime":"Kite","isim":"uçurtma","sifat":"","zarf":"","fiil":"","okunus":"kayt","resimYol":"kite.jpg","btnSmile":false,"btnAngry":false,"btnThink":false,"knowNumber":2},
    {"kelime":"Laughter","isim":"kahkaha, gülme","sifat":"","zarf":"","fiil":"","okunus":"lafter","resimYol":"laughter.jpeg","btnSmile":false,"btnAngry":false,"btnThink":false,"knowNumber":0},
    {"kelime":"Master","isim":"","sifat":"","zarf":"","fiil":"","okunus":"maestır","resimYol":"master.jpg","btnSmile":false,"btnAngry":false,"btnThink":false,"knowNumber":0},
    {"kelime":"Care","isim":"bakım, dikkat","sifat":"","zarf":"","fiil":"ilgilenmek","okunus":"keır","resimYol":"care.jpg","btnSmile":false,"btnAngry":false,"btnThink":false,"knowNumber":0},
]